/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  appDirectory: "app",
  assetsBuildDirectory: "public/build",
  publicPath: "/build/",
  //server: "server.js",
  serverBuildPath: "build/index.js",
  serverModuleFormat: "cjs",
  /*serverDependenciesToBundle: [
    //"@remix-run/express",
    //"@remix-run/node",
    //"@remix-run/react",
    "@stripe/react-stripe-js",
    "@stripe/stripe-js",
    "stripe",
    "@vendia/serverless-express",
    "aws-amplify",
    "compression",
    "cross-env",
    "dotenv",
    "express",
    "isbot",
    "morgan",
    //"react",
    //"react-dom",
  ], */
  future: {
    v2_headers: true,
    v2_errorBoundary: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
};
